[package]
name = "inotify-info-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
rayon = "1.11"
regex = "1.11"
once_cell = "1.21"
nix = { version = "0.30", features = ["fs"] }
colored = "3.0"
thiserror = "2.0"
